os: Visual Studio 2015
version: "{build}"
build: off
platform: x64
environment:
  matrix:
  - nodejs_version: "0.10"
    nodejs_arch: "x86"
  - nodejs_version: "0.10"
    nodejs_arch: "x64"
  - nodejs_version: "0.12"
    nodejs_arch: "x86"
  - nodejs_version: "0.12"
    nodejs_arch: "x64"
  - nodejs_version: "2"
    nodejs_arch: "x86"
  - nodejs_version: "2"
    nodejs_arch: "x64"
  - nodejs_version: "3"
    nodejs_arch: "x86"
  - nodejs_version: "3"
    nodejs_arch: "x64"
install:
  - ps: Install-Product node $env:nodejs_version $env:nodejs_arch
  - node --version
  - npm --version
  - npm install --msvs_version=2013
test_script:
  - npm test
